//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Identity {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Identity() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Base.Resources.Identity", typeof(Identity).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create an instance of .
        /// </summary>
        internal static string cantCreateInstance {
            get {
                return ResourceManager.GetString("cantCreateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string changePasswrd {
            get {
                return ResourceManager.GetString("changePasswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change account settings.
        /// </summary>
        internal static string changeYourAccountSettings {
            get {
                return ResourceManager.GetString("changeYourAccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clicking here.
        /// </summary>
        internal static string clickingHere {
            get {
                return ResourceManager.GetString("clickingHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your account by .
        /// </summary>
        internal static string confirmEmailText {
            get {
                return ResourceManager.GetString("confirmEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        internal static string confirmNewPasswrd {
            get {
                return ResourceManager.GetString("confirmNewPasswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your email.
        /// </summary>
        internal static string confirmYourEmail {
            get {
                return ResourceManager.GetString("confirmYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account..
        /// </summary>
        internal static string createAccount {
            get {
                return ResourceManager.GetString("createAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        internal static string currentPasswrd {
            get {
                return ResourceManager.GetString("currentPasswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete personal data.
        /// </summary>
        internal static string deletePersonalData {
            get {
                return ResourceManager.GetString("deletePersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete data and close my account.
        /// </summary>
        internal static string deletePersonalDataButton {
            get {
                return ResourceManager.GetString("deletePersonalDataButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this data will permanently remove your account, and this cannot be recovered..
        /// </summary>
        internal static string deletePersonalDataNotice {
            get {
                return ResourceManager.GetString("deletePersonalDataNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable two-factor authentication (2FA).
        /// </summary>
        internal static string disable2FA {
            get {
                return ResourceManager.GetString("disable2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable 2FA.
        /// </summary>
        internal static string disable2FAShort {
            get {
                return ResourceManager.GetString("disable2FAShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action only disables 2FA..
        /// </summary>
        internal static string disables2FAOnly {
            get {
                return ResourceManager.GetString("disables2FAOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling 2FA does not change the keys used in authenticator apps. If you wish to change the key used in an authenticator app you should .
        /// </summary>
        internal static string disabling2FAMessage {
            get {
                return ResourceManager.GetString("disabling2FAMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string forgotPassword {
            get {
                return ResourceManager.GetString("forgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        internal static string invalidLoginAttempt {
            get {
                return ResourceManager.GetString("invalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} and at max {1} characters long..
        /// </summary>
        internal static string lengthErrorMessage {
            get {
                return ResourceManager.GetString("lengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage account.
        /// </summary>
        internal static string manageYourAccount {
            get {
                return ResourceManager.GetString("manageYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string newPasswrd {
            get {
                return ResourceManager.GetString("newPasswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string passwrd {
            get {
                return ResourceManager.GetString("passwrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        internal static string passwrdChangedMessage {
            get {
                return ResourceManager.GetString("passwrdChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        internal static string passwrdDoesntMatchError {
            get {
                return ResourceManager.GetString("passwrdDoesntMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        internal static string personalData {
            get {
                return ResourceManager.GetString("personalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        internal static string registerNewUser {
            get {
                return ResourceManager.GetString("registerNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        internal static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend email confirmation.
        /// </summary>
        internal static string resendEmailConfirmation {
            get {
                return ResourceManager.GetString("resendEmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset your authenticator keys..
        /// </summary>
        internal static string resetAuthenticatorKeys {
            get {
                return ResourceManager.GetString("resetAuthenticatorKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string surname {
            get {
                return ResourceManager.GetString("surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication.
        /// </summary>
        internal static string twoFactor {
            get {
                return ResourceManager.GetString("twoFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default UI requires a user store with email support..
        /// </summary>
        internal static string uiRequiresUserStoreWithEmail {
            get {
                return ResourceManager.GetString("uiRequiresUserStoreWithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load user.
        /// </summary>
        internal static string unableToLoadUser {
            get {
                return ResourceManager.GetString("unableToLoadUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred deleting user..
        /// </summary>
        internal static string unexpectedErrorDeletingUser {
            get {
                return ResourceManager.GetString("unexpectedErrorDeletingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update password.
        /// </summary>
        internal static string updatePasswrd {
            get {
                return ResourceManager.GetString("updatePasswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        internal static string useAccountToLogin {
            get {
                return ResourceManager.GetString("useAccountToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        internal static string wrongPasswrd {
            get {
                return ResourceManager.GetString("wrongPasswrd", resourceCulture);
            }
        }
    }
}
